name: Build and Deploy to Kubernetes
on:
  push:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME_USER: ${{ github.repository }}/user-service
  IMAGE_NAME_PRODUCT: ${{ github.repository }}/product-service
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push User Service
      uses: docker/build-push-action@v5
      with:
        context: ./user_service
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_USER }}:latest
    - name: Build and push Product Service
      uses: docker/build-push-action@v5
      with:
        context: ./product_service
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PRODUCT }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/project.yaml